package cli

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"

	"github.com/clebeer/carbon-threat/pkg/extract/compose"
	"github.com/spf13/cobra"
)

// composeFiles are the names docker compose looks for, in its order.
var composeFiles = []string{"compose.yaml", "compose.yml", "docker-compose.yaml", "docker-compose.yml"}

const generatedHeader = `# Generated by ctm. Review this model and commit it next to your code.
#
# Next steps:
#   1. Classify your data under "data:" and reference it from flows ("data:")
#      and datastores ("stores:"). Data-sensitivity rules only fire on
#      classified data.
#   2. Add facts the source cannot express, e.g. properties.authentication,
#      properties.logging, properties.encryptionAtRest, flow "authenticated".
#   3. Run: ctm analyze
#
# Schema: https://github.com/clebeer/carbon-threat/blob/main/schema/ctm-v1.json
`

func newExtractCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "extract",
		Short: "Generate a model from infrastructure definitions",
	}
	var output string
	composeCmd := &cobra.Command{
		Use:   "compose [file]",
		Short: "Generate a model from a Docker Compose file",
		Args:  cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := ""
			if len(args) == 1 {
				path = args[0]
			} else {
				path = findCompose(".")
				if path == "" {
					return &ExitError{Code: ExitFailure, Err: errors.New("no compose file found in the current directory")}
				}
			}
			out, warnings, err := extractCompose(path)
			if err != nil {
				return &ExitError{Code: ExitFailure, Err: err}
			}
			for _, w := range warnings {
				fmt.Fprintln(cmd.ErrOrStderr(), "warning:", w)
			}
			w, closeFn, err := openOutput(cmd, output)
			if err != nil {
				return &ExitError{Code: ExitFailure, Err: err}
			}
			_, err = w.Write(out)
			if cerr := closeFn(); err == nil {
				err = cerr
			}
			if err != nil {
				return &ExitError{Code: ExitFailure, Err: err}
			}
			return nil
		},
	}
	composeCmd.Flags().StringVarP(&output, "output", "o", "", "write the model to a file instead of stdout")
	cmd.AddCommand(composeCmd)
	return cmd
}

func extractCompose(path string) ([]byte, []string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, nil, err
	}
	m, warnings, err := compose.Extract(data, path)
	if err != nil {
		return nil, nil, err
	}
	out, err := compose.Marshal(m)
	if err != nil {
		return nil, nil, err
	}
	return append([]byte(generatedHeader+"\n"), out...), warnings, nil
}

func findCompose(dir string) string {
	for _, name := range composeFiles {
		p := filepath.Join(dir, name)
		if _, err := os.Stat(p); err == nil {
			return p
		}
	}
	return ""
}

const skeleton = generatedHeader + `
apiVersion: ctm/v1
kind: ThreatModel
metadata:
  name: %q
trustZones:
  - id: internet
    name: Internet
    trust: 0
  - id: internal
    name: Internal network
    trust: 80
data:
  - id: user-data
    name: User data
    classification: confidential
components:
  - id: user
    name: User
    type: external_entity
    trustZone: internet
  - id: app
    name: Application
    type: process
    trustZone: internal
    properties:
      authentication: oidc
  - id: db
    name: Database
    type: datastore
    trustZone: internal
    stores: [user-data]
dataFlows:
  - id: user-to-app
    from: user
    to: app
    protocol: https
    authenticated: true
    data: [user-data]
  - id: app-to-db
    from: app
    to: db
    protocol: postgres
    data: [user-data]
`

func newInitCmd() *cobra.Command {
	var force bool
	cmd := &cobra.Command{
		Use:   "init [dir]",
		Short: "Create threatmodel.yaml, generated from the project when possible",
		Long: `Create threatmodel.yaml in dir (default: current directory).

If a Docker Compose file is present the model is generated from it;
otherwise a small example model is written for you to edit.`,
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			dir := "."
			if len(args) == 1 {
				dir = args[0]
			}
			target := filepath.Join(dir, DefaultModelFile)
			if _, err := os.Stat(target); err == nil && !force {
				return &ExitError{Code: ExitFailure, Err: fmt.Errorf("%s already exists (use --force to overwrite)", target)}
			} else if err != nil && !errors.Is(err, fs.ErrNotExist) {
				return &ExitError{Code: ExitFailure, Err: err}
			}

			var content []byte
			if src := findCompose(dir); src != "" {
				out, warnings, err := extractCompose(src)
				if err != nil {
					return &ExitError{Code: ExitFailure, Err: err}
				}
				for _, w := range warnings {
					fmt.Fprintln(cmd.ErrOrStderr(), "warning:", w)
				}
				content = out
				fmt.Fprintf(cmd.OutOrStdout(), "Generated %s from %s.\n", target, src)
			} else {
				name := "my-system"
				if abs, err := filepath.Abs(dir); err == nil {
					name = filepath.Base(abs)
				}
				content = []byte(fmt.Sprintf(skeleton, name))
				fmt.Fprintf(cmd.OutOrStdout(), "No supported source found; wrote an example model to %s.\n", target)
			}
			if err := os.WriteFile(target, content, 0o644); err != nil {
				return &ExitError{Code: ExitFailure, Err: err}
			}
			fmt.Fprintln(cmd.OutOrStdout(), "Next: classify your data in the model, then run `ctm analyze`.")
			return nil
		},
	}
	cmd.Flags().BoolVar(&force, "force", false, "overwrite an existing threatmodel.yaml")
	return cmd
}
