package cli

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/clebeer/carbon-threat/pkg/extract/compose"
	"github.com/clebeer/carbon-threat/pkg/extract/terraform"
	"github.com/clebeer/carbon-threat/pkg/model"
	"github.com/spf13/cobra"
)

// composeFiles are the names docker compose looks for, in its order.
var composeFiles = []string{"compose.yaml", "compose.yml", "docker-compose.yaml", "docker-compose.yml"}

const generatedHeader = `# Generated by ctm. Review this model and commit it next to your code.
#
# Next steps:
#   1. Classify your data under "data:" and reference it from flows ("data:")
#      and datastores ("stores:"). Data-sensitivity rules only fire on
#      classified data.
#   2. Add facts the source cannot express, e.g. properties.authentication,
#      properties.logging, properties.encryptionAtRest, flow "authenticated".
#   3. Run: ctm analyze
#
# Schema: https://github.com/clebeer/carbon-threat/blob/main/schema/ctm-v1.json
`

func newExtractCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "extract",
		Short: "Generate a model from infrastructure definitions",
	}
	var output string
	composeCmd := &cobra.Command{
		Use:   "compose [file]",
		Short: "Generate a model from a Docker Compose file",
		Args:  cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			path := ""
			if len(args) == 1 {
				path = args[0]
			} else {
				path = findCompose(".")
				if path == "" {
					return &ExitError{Code: ExitFailure, Err: errors.New("no compose file found in the current directory")}
				}
			}
			out, warnings, err := extractCompose(path)
			if err != nil {
				return &ExitError{Code: ExitFailure, Err: err}
			}
			for _, w := range warnings {
				fmt.Fprintln(cmd.ErrOrStderr(), "warning:", w)
			}
			w, closeFn, err := openOutput(cmd, output)
			if err != nil {
				return &ExitError{Code: ExitFailure, Err: err}
			}
			_, err = w.Write(out)
			if cerr := closeFn(); err == nil {
				err = cerr
			}
			if err != nil {
				return &ExitError{Code: ExitFailure, Err: err}
			}
			return nil
		},
	}
	composeCmd.Flags().StringVarP(&output, "output", "o", "", "write the model to a file instead of stdout")

	tfCmd := &cobra.Command{
		Use:   "terraform [dir]",
		Short: "Generate a model from Terraform code (AWS) in a directory",
		Long: `Generate a model from the .tf files of one directory (the root module).
Variables, tfvars and locals are evaluated statically; modules are not
followed. Prefer referencing the directory under "sources" in your model, so
it is re-extracted on every run.`,
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			dir := "."
			if len(args) == 1 {
				dir = args[0]
			}
			m, warnings, err := terraform.Extract(os.DirFS(dir), ".")
			if err != nil {
				return &ExitError{Code: ExitFailure, Err: err}
			}
			for _, w := range warnings {
				fmt.Fprintln(cmd.ErrOrStderr(), "warning:", w)
			}
			out, err := compose.Marshal(m)
			if err != nil {
				return &ExitError{Code: ExitFailure, Err: err}
			}
			w, closeFn, err := openOutput(cmd, output)
			if err != nil {
				return &ExitError{Code: ExitFailure, Err: err}
			}
			_, err = w.Write(append([]byte(generatedHeader+"\n"), out...))
			if cerr := closeFn(); err == nil {
				err = cerr
			}
			if err != nil {
				return &ExitError{Code: ExitFailure, Err: err}
			}
			return nil
		},
	}
	tfCmd.Flags().StringVarP(&output, "output", "o", "", "write the model to a file instead of stdout")
	cmd.AddCommand(composeCmd, tfCmd)
	return cmd
}

func extractCompose(path string) ([]byte, []string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, nil, err
	}
	m, warnings, err := compose.Extract(data, path)
	if err != nil {
		return nil, nil, err
	}
	out, err := compose.Marshal(m)
	if err != nil {
		return nil, nil, err
	}
	return append([]byte(generatedHeader+"\n"), out...), warnings, nil
}

func findCompose(dir string) string {
	for _, name := range composeFiles {
		p := filepath.Join(dir, name)
		if _, err := os.Stat(p); err == nil {
			return p
		}
	}
	return ""
}

const skeleton = generatedHeader + `
apiVersion: ctm/v1
kind: ThreatModel
metadata:
  name: %q
trustZones:
  - id: internet
    name: Internet
    trust: 0
  - id: internal
    name: Internal network
    trust: 80
data:
  - id: user-data
    name: User data
    classification: confidential
components:
  - id: user
    name: User
    type: external_entity
    trustZone: internet
  - id: app
    name: Application
    type: process
    trustZone: internal
    properties:
      authentication: oidc
  - id: db
    name: Database
    type: datastore
    trustZone: internal
    stores: [user-data]
dataFlows:
  - id: user-to-app
    from: user
    to: app
    protocol: https
    authenticated: true
    data: [user-data]
  - id: app-to-db
    from: app
    to: db
    protocol: postgres
    data: [user-data]
`

// terraformDirs are conventional places for Terraform code, checked by init.
var terraformDirs = []string{".", "terraform", "infra", "infrastructure", "deploy", "tf"}

// detectSources finds supported infrastructure definitions in dir.
func detectSources(dir string) []model.SourceRef {
	var refs []model.SourceRef
	if src := findCompose(dir); src != "" {
		refs = append(refs, model.SourceRef{Compose: filepath.Base(src)})
	}
	for _, d := range terraformDirs {
		matches, _ := filepath.Glob(filepath.Join(dir, d, "*.tf"))
		if len(matches) > 0 {
			refs = append(refs, model.SourceRef{Terraform: d})
			break
		}
	}
	return refs
}

const overlayHeader = `# Carbon Threat model. Generated by "ctm init".
#
# The sources below are re-extracted every time ctm runs, so this file only
# holds what they cannot express. Entries with the id of an extracted
# component or flow are merged over it; new ids add elements.
#
# Next steps:
#   1. Classify your data under "data:" and reference it from flows ("data:")
#      and datastores ("stores:"). Data-sensitivity rules only fire on
#      classified data.
#   2. Add facts the sources cannot express (authentication, logging,
#      encryption at rest, "authenticated" on flows).
#   3. Run: ctm analyze        (ctm render shows the merged model)
#
# Schema: https://github.com/clebeer/carbon-threat/blob/main/schema/ctm-v1.json
`

func overlayModel(name string, refs []model.SourceRef, m *model.Model) string {
	var b strings.Builder
	b.WriteString(overlayHeader)
	fmt.Fprintf(&b, "\napiVersion: ctm/v1\nkind: ThreatModel\nmetadata:\n  name: %q\nsources:\n", name)
	for _, r := range refs {
		kind, p := r.Kind()
		fmt.Fprintf(&b, "  - %s: %s\n", kind, p)
	}
	var comps, flows []string
	for _, c := range m.Components {
		comps = append(comps, c.ID)
	}
	for _, f := range m.DataFlows {
		flows = append(flows, f.ID)
	}
	fmt.Fprintf(&b, "\n# Extracted components: %s\n", strings.Join(comps, ", "))
	if len(flows) > 0 {
		fmt.Fprintf(&b, "# Extracted flows: %s\n", strings.Join(flows, ", "))
	}
	example := "db"
	for _, c := range m.Components {
		if c.Type == model.TypeDatastore {
			example = c.ID
			break
		}
	}
	fmt.Fprintf(&b, `#
# Example annotations (uncomment and adapt):
#
# data:
#   - id: customer-pii
#     name: Customer PII
#     classification: confidential
#
# components:
#   - id: %s
#     stores: [customer-pii]
#     properties:
#       encryptionAtRest: true
`, example)
	return b.String()
}

func newInitCmd() *cobra.Command {
	var force bool
	cmd := &cobra.Command{
		Use:   "init [dir]",
		Short: "Create threatmodel.yaml, wired to the project's infrastructure when possible",
		Long: `Create threatmodel.yaml in dir (default: current directory).

If a Docker Compose file or Terraform code is found, the model references it
under "sources" so it is re-extracted on every run, and only your
annotations live in the file. Otherwise a small example model is written.`,
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			dir := "."
			if len(args) == 1 {
				dir = args[0]
			}
			target := filepath.Join(dir, DefaultModelFile)
			if _, err := os.Stat(target); err == nil && !force {
				return &ExitError{Code: ExitFailure, Err: fmt.Errorf("%s already exists (use --force to overwrite)", target)}
			} else if err != nil && !errors.Is(err, fs.ErrNotExist) {
				return &ExitError{Code: ExitFailure, Err: err}
			}
			name := "my-system"
			if abs, err := filepath.Abs(dir); err == nil {
				name = filepath.Base(abs)
			}

			var content string
			if refs := detectSources(dir); len(refs) > 0 {
				// Write a minimal model first, then load it to validate the
				// sources and list what they produce.
				minimal := overlayModel(name, refs, &model.Model{})
				m, err := model.Load([]byte(minimal), target, os.DirFS(dir))
				if err != nil {
					return &ExitError{Code: ExitFailure, Err: err}
				}
				for _, w := range m.Warnings {
					fmt.Fprintln(cmd.ErrOrStderr(), "warning:", w)
				}
				content = overlayModel(name, refs, m)
				var names []string
				for _, r := range refs {
					kind, p := r.Kind()
					names = append(names, kind+" "+p)
				}
				fmt.Fprintf(cmd.OutOrStdout(), "Created %s with sources: %s (%d components, %d flows).\n",
					target, strings.Join(names, ", "), len(m.Components), len(m.DataFlows))
			} else {
				content = fmt.Sprintf(skeleton, name)
				fmt.Fprintf(cmd.OutOrStdout(), "No supported source found; wrote an example model to %s.\n", target)
			}
			if err := os.WriteFile(target, []byte(content), 0o644); err != nil {
				return &ExitError{Code: ExitFailure, Err: err}
			}
			fmt.Fprintln(cmd.OutOrStdout(), "Next: classify your data in the model, then run `ctm analyze`.")
			return nil
		},
	}
	cmd.Flags().BoolVar(&force, "force", false, "overwrite an existing threatmodel.yaml")
	return cmd
}

func newRenderCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "render [model]",
		Short: "Print the model with its sources extracted and merged",
		Args:  cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			m, err := loadModel(cmd, modelArg(args))
			if err != nil {
				return &ExitError{Code: ExitFailure, Err: err}
			}
			m.Sources = nil
			out, err := compose.Marshal(m)
			if err != nil {
				return &ExitError{Code: ExitFailure, Err: err}
			}
			fmt.Fprintf(cmd.OutOrStdout(), "# Resolved model for %s (sources extracted and merged). Generated by ctm render.\n", m.Source)
			_, err = cmd.OutOrStdout().Write(out)
			return err
		},
	}
}
