export const DEFAULT_STENCIL: { kind: string; label: string }[] = [
  { kind: 'server', label: 'Server' },
  { kind: 'db',     label: 'Database' },
  { kind: 'fw',     label: 'Firewall' },
  { kind: 'user',   label: 'Actor' },
  { kind: 'api',    label: 'API' },
  { kind: 'cloud',  label: 'Cloud' },
  { kind: 'browser',label: 'Client' },
  // Network assets
  { kind: 'router', label: 'Router' },
  { kind: 'switch', label: 'Switch' },
  { kind: 'loadbalancer', label: 'LB' },
  { kind: 'vpn',    label: 'VPN' },
  { kind: 'dns',    label: 'DNS' },
  { kind: 'waf',    label: 'WAF' },
  { kind: 'ids',    label: 'IDS' },
  { kind: 'siem',   label: 'SIEM' },
  { kind: 'endpoint', label: 'Endpoint' },
  { kind: 'iot',    label: 'IoT' },
  { kind: 'laptop', label: 'Laptop' },
  { kind: 'hub',    label: 'Hub' },
  { kind: 'access-point', label: 'Wi-Fi' },
  { kind: 'nas',    label: 'NAS' },
  { kind: 'bastion', label: 'Bastion' },
  // Cloud assets
  { kind: 'k8s-cluster', label: 'K8s' },
  { kind: 'container', label: 'Container' },
  { kind: 'queue',   label: 'Queue' },
  { kind: 'cache',   label: 'Cache' },
  { kind: 'monitoring', label: 'Monitor' },
  { kind: 'vault',   label: 'Vault' },
  { kind: 'iam',     label: 'IAM' },
  { kind: 'gitops',  label: 'CI/CD' },
  { kind: 'cdn',     label: 'CDN' },
  // Trust boundary
  { kind: 'trust-boundary', label: 'Boundary' },
];