// Package compose builds a ctm/v1 model from a Docker Compose file.
//
// It records only facts that the file states: services become components,
// published ports become flows from the internet, depends_on/links and
// connection strings become flows between services. It never guesses data
// classification; users add that by hand.
package compose

import (
	"fmt"
	"net/url"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/clebeer/carbon-threat/pkg/model"
	"go.yaml.in/yaml/v3"
)

// Trust levels of the zones the extractor creates.
const (
	internetTrust = 0
	edgeTrust     = 30
	internalTrust = 70
)

// datastoreTech maps substrings of an image reference to a technology and
// the protocol clients use to reach it.
var datastoreTech = []struct{ match, tech, protocol string }{
	{"postgis", "postgres", "postgres"},
	{"timescale", "postgres", "postgres"},
	{"postgres", "postgres", "postgres"},
	{"mariadb", "mariadb", "mysql"},
	{"mysql", "mysql", "mysql"},
	{"mssql", "mssql", "tds"},
	{"mongo", "mongodb", "mongodb"},
	{"valkey", "valkey", "redis"},
	{"keydb", "keydb", "redis"},
	{"redis", "redis", "redis"},
	{"memcached", "memcached", "memcached"},
	{"elasticsearch", "elasticsearch", "http"},
	{"opensearch", "opensearch", "http"},
	{"cassandra", "cassandra", "cql"},
	{"couchdb", "couchdb", "http"},
	{"neo4j", "neo4j", "bolt"},
	{"clickhouse", "clickhouse", "http"},
	{"influxdb", "influxdb", "http"},
	{"cockroach", "cockroachdb", "postgres"},
	{"minio", "minio", "http"},
	{"rabbitmq", "rabbitmq", "amqp"},
	{"kafka", "kafka", "kafka"},
	{"nats", "nats", "nats"},
}

var (
	secretKey   = regexp.MustCompile(`(?i)(PASSWORD|PASSWD|SECRET(_?KEY)?|TOKEN|API_?KEY|PRIVATE_?KEY|ACCESS_?KEY|CREDENTIALS?)$`)
	hostKey     = regexp.MustCompile(`(?i)(HOST|HOSTNAME|SERVER|ADDR|ADDRESS)$`)
	urlInValue  = regexp.MustCompile(`[a-zA-Z][a-zA-Z0-9+.-]*://[^\s"']+`)
	invalidID   = regexp.MustCompile(`[^a-z0-9._-]+`)
	schemeAlias = map[string]string{"postgresql": "postgres", "mongodb+srv": "mongodb", "mysql2": "mysql", "redis+tls": "rediss"}
)

type file struct {
	Name     string             `yaml:"name"`
	Services map[string]service `yaml:"services"`
}

type service struct {
	Image       string    `yaml:"image"`
	Privileged  *bool     `yaml:"privileged"`
	Ports       []any     `yaml:"ports"`
	Environment yaml.Node `yaml:"environment"`
	DependsOn   yaml.Node `yaml:"depends_on"`
	Links       []string  `yaml:"links"`
}

// Extract converts a compose file to a model. path is used for the model
// name and messages. It returns warnings for things it could not interpret.
func Extract(data []byte, path string) (*model.Model, []string, error) {
	var f file
	if err := yaml.Unmarshal(data, &f); err != nil {
		return nil, nil, fmt.Errorf("%s: %w", path, err)
	}
	if len(f.Services) == 0 {
		return nil, nil, fmt.Errorf("%s: no services found", path)
	}
	var warnings []string

	names := make([]string, 0, len(f.Services))
	for n := range f.Services {
		names = append(names, n)
	}
	sort.Strings(names)
	ids := map[string]string{} // service name -> component id
	for _, n := range names {
		ids[n] = toID(n)
	}

	m := &model.Model{
		APIVersion: model.APIVersion,
		Kind:       model.Kind,
		Metadata: model.Metadata{
			Name:        modelName(f.Name, path),
			Description: "Generated by ctm extract compose from " + filepath.Base(path) + ". Review it: classify data, then add facts the compose file cannot express (authentication, logging, encryption at rest).",
		},
	}

	exposed := map[string][]int{} // service -> published container ports
	for _, n := range names {
		ports, warn := publishedPorts(f.Services[n].Ports)
		for _, w := range warn {
			warnings = append(warnings, fmt.Sprintf("service %s: %s", n, w))
		}
		if len(ports) > 0 {
			exposed[n] = ports
		}
	}

	if len(exposed) > 0 {
		m.TrustZones = append(m.TrustZones,
			model.TrustZone{ID: "internet", Name: "Internet", Trust: internetTrust},
			model.TrustZone{ID: "edge", Name: "Published ports", Trust: edgeTrust},
		)
		m.Components = append(m.Components, model.Component{
			ID: "internet", Name: "Internet clients", Type: model.TypeExternalEntity, TrustZone: "internet",
		})
	}
	m.TrustZones = append(m.TrustZones, model.TrustZone{ID: "internal", Name: "Compose network", Trust: internalTrust})

	protocolOf := map[string]string{}
	for _, n := range names {
		s := f.Services[n]
		c := model.Component{ID: ids[n], Name: n, Type: model.TypeProcess, TrustZone: "internal"}
		if _, ok := exposed[n]; ok {
			c.TrustZone = "edge"
		}
		if tech, proto, ok := datastore(s.Image); ok {
			c.Type = model.TypeDatastore
			c.Technology = tech
			protocolOf[n] = proto
		}
		c.Properties.Image = s.Image
		if s.Privileged != nil {
			c.Properties.Privileged = model.Bool(*s.Privileged)
		}
		if hasHardcodedSecret(environment(&s.Environment)) {
			c.Properties.HardcodedSecrets = model.Bool(true)
		}
		m.Components = append(m.Components, c)
	}

	// Flows from the internet are kept per published port, because one
	// service may publish both a plaintext and a TLS port.
	type key struct {
		from, to string
		port     int
	}
	flows := map[key]*model.DataFlow{}
	var order []key
	addFlow := func(from, to string, port int, protocol string, encrypted *bool) {
		k := key{from, to, port}
		fl, ok := flows[k]
		if !ok {
			id := from + "-to-" + to
			if port > 0 {
				id += "-" + strconv.Itoa(port)
			}
			fl = &model.DataFlow{ID: id, From: from, To: to}
			flows[k] = fl
			order = append(order, k)
		}
		if fl.Protocol == "" {
			fl.Protocol = protocol
		}
		if fl.Encrypted == nil && encrypted != nil {
			fl.Encrypted = encrypted
		}
	}

	for _, n := range names {
		for _, p := range exposed[n] {
			proto := ""
			switch {
			case p == 443 || p == 8443:
				proto = "https"
			case p == 80 || p == 8080:
				proto = "http"
			case protocolOf[n] != "":
				proto = protocolOf[n]
			}
			addFlow("internet", ids[n], p, proto, nil)
		}
	}
	for _, n := range names {
		s := f.Services[n]
		env := environment(&s.Environment)
		for _, dep := range dependsOn(&s.DependsOn, s.Links) {
			if _, ok := ids[dep]; ok && dep != n {
				addFlow(ids[n], ids[dep], 0, protocolOf[dep], nil)
			}
		}
		for _, k := range sortedKeys(env) {
			v := env[k]
			for _, raw := range urlInValue.FindAllString(v, -1) {
				u, err := url.Parse(raw)
				if err != nil {
					continue
				}
				target := u.Hostname()
				if _, ok := ids[target]; !ok || target == n {
					continue
				}
				scheme := strings.ToLower(u.Scheme)
				if a, ok := schemeAlias[scheme]; ok {
					scheme = a
				}
				addFlow(ids[n], ids[target], 0, scheme, sslMode(u))
			}
			if hostKey.MatchString(k) {
				if _, ok := ids[v]; ok && v != n {
					addFlow(ids[n], ids[v], 0, protocolOf[v], nil)
				}
			}
		}
	}
	for _, k := range order {
		m.DataFlows = append(m.DataFlows, *flows[k])
	}

	// Validate what we produced, so extractor bugs surface here and not as
	// confusing errors in a later "ctm analyze".
	out, err := Marshal(m)
	if err != nil {
		return nil, nil, err
	}
	if _, err := model.Parse(out, path+" (extracted)"); err != nil {
		return nil, nil, fmt.Errorf("internal error: extracted model is invalid: %w", err)
	}
	return m, warnings, nil
}

// Marshal renders a model as YAML with two-space indentation.
func Marshal(m *model.Model) ([]byte, error) {
	var b strings.Builder
	enc := yaml.NewEncoder(&b)
	enc.SetIndent(2)
	if err := enc.Encode(m); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return []byte(b.String()), nil
}

func modelName(name, path string) string {
	if name != "" {
		return name
	}
	abs, err := filepath.Abs(path)
	if err != nil {
		return "compose"
	}
	return filepath.Base(filepath.Dir(abs))
}

func toID(name string) string {
	id := invalidID.ReplaceAllString(strings.ToLower(name), "-")
	id = strings.TrimLeft(id, "._-")
	if id == "" {
		id = "service"
	}
	return id
}

func datastore(image string) (tech, protocol string, ok bool) {
	img := strings.ToLower(image)
	if i := strings.Index(img, "@"); i >= 0 {
		img = img[:i]
	}
	// Ignore the tag so "app:redis-cache" is not taken for redis.
	if i := strings.LastIndex(img, ":"); i > strings.LastIndex(img, "/") {
		img = img[:i]
	}
	for _, d := range datastoreTech {
		if strings.Contains(img, d.match) {
			return d.tech, d.protocol, true
		}
	}
	return "", "", false
}

// publishedPorts returns the container ports published on a non-loopback
// host interface.
func publishedPorts(ports []any) ([]int, []string) {
	var out []int
	var warnings []string
	for _, p := range ports {
		switch v := p.(type) {
		case string:
			if port, ok, err := parseShortPort(v); err != nil {
				warnings = append(warnings, err.Error())
			} else if ok {
				out = append(out, port)
			}
		case int:
			// A bare container port is published on a random host port.
			out = append(out, v)
		case map[string]any:
			hostIP, _ := v["host_ip"].(string)
			if isLoopback(hostIP) {
				continue
			}
			if _, published := v["published"]; !published {
				continue
			}
			switch t := v["target"].(type) {
			case int:
				out = append(out, t)
			case string:
				if n, err := strconv.Atoi(t); err == nil {
					out = append(out, n)
				}
			}
		default:
			warnings = append(warnings, fmt.Sprintf("unrecognized port entry %v", p))
		}
	}
	return out, warnings
}

// parseShortPort handles "80", "8080:80", "127.0.0.1:5432:5432",
// "[::1]:80:80", "8000-8001:8000-8001" and an optional "/proto" suffix.
func parseShortPort(s string) (port int, published bool, err error) {
	s = strings.TrimSpace(s)
	if i := strings.Index(s, "/"); i >= 0 {
		s = s[:i]
	}
	hostIP := ""
	if strings.HasPrefix(s, "[") {
		end := strings.Index(s, "]")
		if end < 0 {
			return 0, false, fmt.Errorf("cannot parse port %q", s)
		}
		hostIP = s[1:end]
		s = strings.TrimPrefix(s[end+1:], ":")
	}
	parts := strings.Split(s, ":")
	if len(parts) == 3 {
		hostIP, parts = parts[0], parts[1:]
	}
	if isLoopback(hostIP) {
		return 0, false, nil
	}
	target := parts[len(parts)-1]
	if i := strings.Index(target, "-"); i >= 0 {
		target = target[:i]
	}
	n, convErr := strconv.Atoi(target)
	if convErr != nil {
		return 0, false, fmt.Errorf("cannot parse port %q", s)
	}
	return n, true, nil
}

func isLoopback(ip string) bool {
	return ip == "127.0.0.1" || ip == "::1" || ip == "localhost" || strings.HasPrefix(ip, "127.")
}

// environment reads the list ("KEY=value") or map form.
func environment(n *yaml.Node) map[string]string {
	out := map[string]string{}
	switch n.Kind {
	case yaml.SequenceNode:
		for _, item := range n.Content {
			k, v, _ := strings.Cut(item.Value, "=")
			out[k] = v
		}
	case yaml.MappingNode:
		for i := 0; i+1 < len(n.Content); i += 2 {
			v := n.Content[i+1]
			if v.Tag == "!!null" {
				out[n.Content[i].Value] = ""
				continue
			}
			out[n.Content[i].Value] = v.Value
		}
	}
	return out
}

func dependsOn(n *yaml.Node, links []string) []string {
	var out []string
	switch n.Kind {
	case yaml.SequenceNode:
		for _, item := range n.Content {
			out = append(out, item.Value)
		}
	case yaml.MappingNode:
		for i := 0; i+1 < len(n.Content); i += 2 {
			out = append(out, n.Content[i].Value)
		}
	}
	for _, l := range links {
		name, _, _ := strings.Cut(l, ":")
		out = append(out, name)
	}
	return out
}

func hasHardcodedSecret(env map[string]string) bool {
	for k, v := range env {
		if v == "" || strings.Contains(v, "${") || strings.HasPrefix(v, "$") || strings.HasPrefix(v, "/run/secrets/") {
			continue
		}
		if secretKey.MatchString(k) && !strings.HasSuffix(strings.ToUpper(k), "_FILE") {
			return true
		}
		for _, raw := range urlInValue.FindAllString(v, -1) {
			if u, err := url.Parse(raw); err == nil {
				if pw, ok := u.User.Password(); ok && pw != "" && !strings.Contains(pw, "$") {
					return true
				}
			}
		}
	}
	return false
}

// sslMode reads PostgreSQL-style sslmode / generic ssl/tls query parameters.
func sslMode(u *url.URL) *bool {
	q := u.Query()
	for _, k := range []string{"sslmode", "ssl", "tls"} {
		switch strings.ToLower(q.Get(k)) {
		case "disable", "false", "0":
			return model.Bool(false)
		case "require", "verify-ca", "verify-full", "true", "1":
			return model.Bool(true)
		}
	}
	return nil
}

func sortedKeys(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
